name: pokedex_app

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.0
  get: ^4.6.5
  intl: ^0.17.0
  dio: ^4.0.6
  flutter_neumorphic: ^3.2.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  syncfusion_flutter_charts: ^20.4.43
  cached_network_image: ^3.2.3
  flutter_localizations: 
    sdk: flutter 


dev_dependencies:
  flutter_test:
    sdk: flutter

 

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/


   

